import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-hidden h-screen">
        {" "}
        <div className="h-full flex justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
